name: slack
description: "Slack client for Fix Inventory"
version: "1.0.0"
language: jinja2
license: "Apache 2.0"
authors: ["someengineering"]
url: "https://inventory.fix.security/"
categories: ["notification"]
default_config:
  slack:
    webhook: 'https://hooks.slack.com/services/T04JZG5SZR3/B03E6JYPWCR/abcdefghijklmnopqrstuvwxyz'
config_schema:
  - fqn: slack
    bases: []
    properties:
    - name: webhook
      kind: string
      required: true
      description: Slack Webhook URL.
args_schema:
  title:
    help: "Title of the message to send to Slack."
    type: str
    required: true
  message:
    help: "Message that comes before the resources."
    type: str
    default: "Fix found the following resources:"
  webhook:
    help: "Optional Slack Webhook URL."
    type: str
    default: null
    required: false
  key:
    help: "Resource field to show as key."
    type: str
    default: "kind"
    required: false
  value:
    help: "Resource field to show as value."
    type: str
    default: "name"
    required: false
