name: tagvalidator
description: "Tag Validator app for Fix Inventory."
version: "1.0.0"
language: jinja2
license: "Apache 2.0"
authors: ["someengineering"]
url: "https://inventory.fix.security/"
categories: ["tagging"]
default_config:
  tagvalidator:
    default:
      expiration: '24h'
    kinds:
      - 'aws_ec2_instance'
      - 'aws_vpc'
      - 'aws_cloudformation_stack'
      - 'aws_elb'
      - 'aws_alb'
      - 'aws_alb_target_group'
      - 'aws_eks_cluster'
      - 'aws_eks_nodegroup'
      - 'aws_ec2_nat_gateway'
    accounts:
      aws:
        '139475575661':
          name: 'eng-production'
        '123415487488':
          name: 'sales-hosted-lead-gen'
          expiration: '8d'
config_schema:
  - fqn: tagvalidator
    bases: []
    properties:
    - name: default
      kind: dictionary[string, string]
      required: false
      description: Default expiration if not otherwise specified.
    - name: kinds
      kind: string[]
      required: false
      description: List of kinds to validate expiration tags on.
    - name: accounts
      kind: dictionary[string, dictionary[string, dictionary[string, string]]]
      required: false
      description: Clouds and accounts to cleanup AWS alarms in.
    allow_unknown_props: false
    successor_kinds: null
    aggregate_root: true
    metadata: null
args_schema:
