name: cleanup-untagged
description: "This app deletes cloud resources that are missing mandatory tags after a certain amount of time has passed since their creation."
version: "1.0.0"
language: jinja2
license: "Apache 2.0"
authors: ["someengineering"]
url: "https://resoto.com/"
categories: ["cleanup"]
default_config:
  default:
    age: '2h'
  tags:
    - 'owner'
    - 'expiration'
  kinds:
    - 'aws_ec2_instance'
    - 'aws_ec2_volume'
    - 'aws_vpc'
    - 'aws_cloudformation_stack'
    - 'aws_elb'
    - 'aws_alb'
    - 'aws_alb_target_group'
    - 'aws_eks_cluster'
    - 'aws_eks_nodegroup'
    - 'example_instance'
    - 'example_network'
  accounts:
    aws:
      '068564737731':
        name: 'playground'
        age: '7d'
      '575584959047':
        name: 'eng-sre'
config_schema:
  - fqn: cleanup_untagged
    bases: []
    properties:
    - name: default
      kind: dictionary[string, string]
      required: false
      description: Default age after which tags must exist.
    - name: tags
      kind: string[]
      required: false
      description: List of mandatory tags.
    - name: kinds
      kind: string[]
      required: false
      description: Kinds that should be checked for tags.
    - name: accounts
      kind: dictionary[string, dictionary[string, dictionary[string, string]]]
      required: false
      description: Accounts to run the app on.
    allow_unknown_props: false
    successor_kinds: null
    aggregate_root: true
    metadata: null
args_schema:
