name: cleanup-volumes
description: "This app cleans up unused storage volumes that have reached a certain age threshold."
version: "1.0.0"
language: jinja2
license: "Apache 2.0"
authors: ["someengineering"]
url: "https://inventory.fix.security/"
categories: ["cleanup"]
default_config:
  cleanup_volumes:
    min_age: '30d'
config_schema:
  - fqn: cleanup_volumes
    bases: []
    properties:
    - name: min_age
      kind: string
      required: true
      description: Minimum age of unused volumes to cleanup.
args_schema:
